# PROJECT - Manufacturing Quality Control & Predictive Maintenance

## Project Overview

This project focuses on analyzing manufacturing operations to improve product quality, reduce machine failures, minimize downtime, and optimize maintenance activities.

The dataset represents a manufacturing company operating multiple factories, production lines, machines, suppliers, and operators. It also includes production batches, sensor readings, machine failures, maintenance work orders, quality inspections, and downtime events.

The project will cover:

- Data Understanding
- Data Cleaning
- Exploratory Data Analysis
- Statistical Analysis
- SQL Database Design
- Machine Learning
- Power BI Dashboard
- Business Recommendations
---

## Business Problem

The manufacturing company is experiencing several operational challenges:

- Increasing machine failures
- High production downtime
- Rising maintenance costs
- Product quality issues
- High scrap and rework
- Supplier quality variations
- Production inefficiencies

Management wants to understand the root causes behind these issues and identify opportunities to improve operational efficiency while reducing costs.

In [2]:
# Importing essential libraries 
import pandas as pd 
import numpy as np 

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

In [3]:
data_path = "../📁Data/📁Raw_data/"

In [4]:
factories = pd.read_csv(data_path + "factories.csv")
production_lines = pd.read_csv(data_path + "production_lines.csv")
machines = pd.read_csv(data_path + "machines.csv")
suppliers = pd.read_csv(data_path + "suppliers.csv")
products = pd.read_csv(data_path + "products.csv")
operators = pd.read_csv(data_path + "operators.csv")
production_batches = pd.read_csv(data_path + "production_batches.csv")
sensor_readings = pd.read_csv(data_path + "sensor_readings.csv")
maintenance_work_orders = pd.read_csv(data_path + "maintenance_work_orders.csv")
quality_inspections = pd.read_csv(data_path + "quality_inspections.csv")
downtime_events = pd.read_csv(data_path + "downtime_events.csv")
failure_events = pd.read_csv(data_path + "failure_events.csv")

In [5]:
datasets = {
    "Factories": factories,
    "Production Lines": production_lines,
    "Machines": machines,
    "Suppliers": suppliers,
    "Products": products,
    "Operators": operators,
    "Production Batches": production_batches,
    "Sensor Readings": sensor_readings,
    "Maintenance Work Orders": maintenance_work_orders,
    "Quality Inspections": quality_inspections,
    "Downtime Events": downtime_events,
    "Failure Events": failure_events
}

In [6]:
summary = pd.DataFrame({
    "Dataset": datasets.keys(),
    "Rows":[df.shape[0] for df in datasets.values()],
    "Columns":[df.shape[1] for df in datasets.values()]
})

summary

                    Dataset    Rows  Columns
0                 Factories      10        9
1          Production Lines      30        7
2                  Machines     600       17
3                 Suppliers     210        8
4                  Products     150       10
5                 Operators    1000        9
6        Production Batches   60000       24
7           Sensor Readings  285000       17
8   Maintenance Work Orders   12000       16
9       Quality Inspections   30000       18
10          Downtime Events    8000       13
11           Failure Events    3000       11

## Dataset Summary

All datasets were successfully loaded into the notebook. The project contains 12 related tables representing different stages of the manufacturing process, including factories, production, quality inspections, machine failures, maintenance activities, and sensor monitoring.

In [13]:
def inspect_dataset(df,name):

    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)

    print(f"\nShape: {df.shape}")

    print("\nData Types:")
    display(df.dtypes)

    print("\nDataset Information:")
    df.info()

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\nLast 5 Rows:")
    display(df.tail())

In [14]:
for name, df in datasets.items():
    inspect_dataset(df, name)

================================================================================
Dataset: Factories
================================================================================

Shape: (10, 9)

Data Types:

factory_id            str
factory_name          str
city                  str
state                 str
region                str
specialization        str
employee_count      int64
target_oee        float64
certification         str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   factory_id      10 non-null     str
 1   factory_name    10 non-null     str
 2   city            10 non-null     str
 3   state           10 non-null     str
 4   region          10 non-null     str
 5   specialization  10 non-null     str
 6   employee_count  10 non-null     int64
 7   target_oee      10 non-null     float64
 8   certification   10 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 852.0 bytes

First 5 Rows:

,factory_id,factory_name,city,state,region,specialization,employee_count,target_oee,certification
0,FAC001,Pune Manufacturing Plant,Pune,Maharashtra,West,Automotive Components,1529,0.84,IATF 16949
1,FAC002,Chennai Manufacturing Plant,Chennai,Tamil Nadu,South,Industrial Motors,710,0.92,ISO 9001
2,FAC003,Gurugram Manufacturing Plant,Gurugram,Haryana,North,Precision Parts,1772,0.95,IATF 16949
3,FAC004,Ahmedabad Manufacturing Plant,Ahmedabad,Gujarat,West,Packaging Equipment,1672,0.88,IATF 16949
4,FAC005,Bengaluru Manufacturing Plant,Bengaluru,Karnataka,South,Electronics Assembly,2090,0.95,ISO 9001 + ISO 14001

Last 5 Rows:

,factory_id,factory_name,city,state,region,specialization,employee_count,target_oee,certification
5,FAC006,Jamshedpur Manufacturing Plant,Jamshedpur,Jharkhand,East,Heavy Engineering,1701,0.93,ISO 9001 + ISO 14001
6,FAC007,Noida Manufacturing Plant,Noida,Uttar Pradesh,North,Consumer Appliances,1757,0.86,ISO 9001
7,FAC008,Kolkata Manufacturing Plant,Kolkata,West Bengal,East,Pumps & Valves,2172,0.84,ISO 9001
8,FAC009,Hyderabad Manufacturing Plant,Hyderabad,Telangana,South,Control Systems,2168,0.89,IATF 16949
9,FAC010,Indore Manufacturing Plant,Indore,Madhya Pradesh,Central,Metal Fabrication,1143,0.89,ISO 9001

================================================================================
Dataset: Production Lines
================================================================================

Shape: (30, 7)

Data Types:

line_id                   str
factory_id                str
line_name                 str
line_type                 str
daily_capacity_units    int64
shift_pattern             str
line_status               str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   line_id               30 non-null     str
 1   factory_id            30 non-null     str
 2   line_name             30 non-null     str
 3   line_type             30 non-null     str
 4   daily_capacity_units  30 non-null     int64
 5   shift_pattern         30 non-null     str
 6   line_status           30 non-null     str
dtypes: int64(1), str(6)
memory usage: 1.8 KB

First 5 Rows:

,line_id,factory_id,line_name,line_type,daily_capacity_units,shift_pattern,line_status
0,LIN001,FAC001,Heat Treatment Line 01,Heat Treatment,1530,3 Shift,Active
1,LIN002,FAC001,Heat Treatment Line 02,Heat Treatment,3555,Continuous,Active
2,LIN003,FAC001,Packaging Line 03,Packaging,1894,2 Shift,Active
3,LIN004,FAC002,Molding Line 04,Molding,2373,2 Shift,Active
4,LIN005,FAC002,Machining Line 05,Machining,3972,Continuous,Active

Last 5 Rows:

,line_id,factory_id,line_name,line_type,daily_capacity_units,shift_pattern,line_status
25,LIN026,FAC009,Heat Treatment Line 26,Heat Treatment,1249,3 Shift,Standby
26,LIN027,FAC009,Machining Line 27,Machining,3156,3 Shift,Standby
27,LIN028,FAC010,Molding Line 28,Molding,895,2 Shift,Standby
28,LIN029,FAC010,Assembly Line 29,Assembly,2340,2 Shift,Active
29,LIN030,FAC010,Machining Line 30,Machining,2348,Continuous,Active

================================================================================
Dataset: Machines
================================================================================

Shape: (600, 17)

Data Types:

machine_id                           str
line_id                              str
factory_id                           str
machine_type                         str
brand                                str
model                                str
installation_date                    str
machine_age_years                float64
criticality                          str
rated_capacity_units_per_hour      int64
normal_temperature_c               int64
warning_temperature_c              int64
normal_rpm_min                     int64
normal_rpm_max                     int64
baseline_vibration_mm_s          float64
base_failure_probability         float64
machine_status                       str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   machine_id                     600 non-null    str
 1   line_id                        600 non-null    str
 2   factory_id                     600 non-null    str
 3   machine_type                   600 non-null    str
 4   brand                          600 non-null    str
 5   model                          600 non-null    str
 6   installation_date              600 non-null    str
 7   machine_age_years              600 non-null    float64
 8   criticality                    600 non-null    str
 9   rated_capacity_units_per_hour  600 non-null    int64
 10  normal_temperature_c           600 non-null    int64
 11  warning_temperature_c          600 non-null    int64
 12  normal_rpm_min                 600 non-null    int64
 13  normal_rpm_max                 600 non-null    int64
 14  baseline_vibration_mm_s        600 non-null    float64
 15  base_failure_probability       600 non-null    float64
 16  machine_status                 600 non-null    str
dtypes: float64(3), int64(5), str(9)
memory usage: 79.8 KB

First 5 Rows:

,machine_id,line_id,factory_id,machine_type,brand,model,installation_date,machine_age_years,criticality,rated_capacity_units_per_hour,normal_temperature_c,warning_temperature_c,normal_rpm_min,normal_rpm_max,baseline_vibration_mm_s,base_failure_probability,machine_status
0,MCH0001,LIN020,FAC007,Injection Molding,Husky,HUS-145,2015-07-24,10.90,Medium,464,55,75,1200,1900,3.00,0.04,Standby
1,MCH0002,LIN009,FAC003,Industrial Furnace,Thermax,THE-780,2013-06-21,13.00,Low,378,350,520,0,0,1.50,0.05,Standby
2,MCH0003,LIN025,FAC009,Packaging Line,Krones,KRO-584,2013-01-09,13.50,High,381,40,65,700,1300,2.00,0.08,Active
3,MCH0004,LIN020,FAC007,Assembly Robot,ABB,ABB-263,2011-11-23,14.60,Medium,149,45,70,1400,2100,2.20,0.06,Standby
4,MCH0005,LIN010,FAC004,Grinding Machine,Bosch Rexroth,BOS-632,2018-10-04,7.70,High,493,65,82,1500,2300,3.40,0.06,Active

Last 5 Rows:

,machine_id,line_id,factory_id,machine_type,brand,model,installation_date,machine_age_years,criticality,rated_capacity_units_per_hour,normal_temperature_c,warning_temperature_c,normal_rpm_min,normal_rpm_max,baseline_vibration_mm_s,base_failure_probability,machine_status
595,MCH0596,LIN022,FAC008,Grinding Machine,Bosch Rexroth,BOS-373,2022-04-28,4.20,Medium,382,65,82,1500,2300,3.40,0.03,Standby
596,MCH0597,LIN012,FAC004,CNC Milling,Makino,MAK-315,2023-09-13,2.80,Critical,210,72,85,1800,2400,2.80,0.05,Active
597,MCH0598,LIN029,FAC010,Injection Molding,Husky,HUS-999,2010-07-29,15.90,Medium,245,55,75,1200,1900,3.00,0.06,Active
598,MCH0599,LIN003,FAC001,Packaging Line,Krones,KRO-272,2015-01-29,11.40,Medium,355,40,65,700,1300,2.00,0.05,Active
599,MCH0600,LIN014,FAC005,Injection Molding,Husky,HUS-912,2011-10-21,14.70,Medium,155,55,75,1200,1900,3.00,0.06,Under Maintenance

================================================================================
Dataset: Suppliers
================================================================================

Shape: (210, 8)

Data Types:

supplier_id                   str
supplier_name                 str
region                        str
supplier_category             str
quality_rating            float64
average_lead_time_days      int64
delivery_reliability      float64
supplier_status               str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   supplier_id             210 non-null    str
 1   supplier_name           210 non-null    str
 2   region                  210 non-null    str
 3   supplier_category       210 non-null    str
 4   quality_rating          210 non-null    float64
 5   average_lead_time_days  210 non-null    int64
 6   delivery_reliability    210 non-null    float64
 7   supplier_status         210 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 13.3 KB

First 5 Rows:

,supplier_id,supplier_name,region,supplier_category,quality_rating,average_lead_time_days,delivery_reliability,supplier_status
0,SUP0001,Industrial Supplier 001,West,Electronic Parts,0.94,33,0.90,Approved
1,SUP0002,Industrial Supplier 002,East,Mechanical Parts,0.83,8,0.88,Approved
2,SUP0003,Industrial Supplier 003,South,Electronic Parts,0.95,9,0.82,Approved
3,SUP0004,Industrial Supplier 004,West,Electronic Parts,0.95,6,0.89,Approved
4,SUP0005,Industrial Supplier 005,North,Mechanical Parts,0.85,35,0.83,Approved

Last 5 Rows:

,supplier_id,supplier_name,region,supplier_category,quality_rating,average_lead_time_days,delivery_reliability,supplier_status
205,SUP0206,Industrial Supplier 206,West,Mechanical Parts,0.95,28,0.93,Approved
206,SUP0207,Industrial Supplier 207,North,Raw Material,0.93,18,0.88,Approved
207,SUP0208,Industrial Supplier 208,West,Raw Material,0.86,25,0.81,Approved
208,SUP0209,Industrial Supplier 209,East,Mechanical Parts,0.88,27,0.91,Conditional
209,SUP0210,Industrial Supplier 210,West,Raw Material,0.84,24,0.92,Approved

================================================================================
Dataset: Products
================================================================================

Shape: (150, 10)

Data Types:

product_id                       str
supplier_id                      str
product_name                     str
product_category                 str
material                         str
process_complexity               str
target_cycle_time_minutes    float64
standard_unit_cost_inr       float64
dimensional_tolerance_mm     float64
quality_grade                    str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   product_id                 150 non-null    str
 1   supplier_id                150 non-null    str
 2   product_name               150 non-null    str
 3   product_category           150 non-null    str
 4   material                   150 non-null    str
 5   process_complexity         150 non-null    str
 6   target_cycle_time_minutes  150 non-null    float64
 7   standard_unit_cost_inr     150 non-null    float64
 8   dimensional_tolerance_mm   150 non-null    float64
 9   quality_grade              150 non-null    str
dtypes: float64(3), str(7)
memory usage: 11.8 KB

First 5 Rows:

,product_id,supplier_id,product_name,product_category,material,process_complexity,target_cycle_time_minutes,standard_unit_cost_inr,dimensional_tolerance_mm,quality_grade
0,PRD0001,SUP0143,Packaging Unit 001,Packaging Unit,ABS Plastic,Medium,4.24,5072.36,0.42,A
1,PRD0002,SUP0183,Electrical Component 002,Electrical Component,Steel,High,4.36,5589.11,0.25,C
2,PRD0003,SUP0011,Automotive Part 003,Automotive Part,Aluminium,Low,7.03,849.10,0.28,A
3,PRD0004,SUP0073,Automotive Part 004,Automotive Part,Composite,Low,5.58,2074.65,0.13,A
4,PRD0005,SUP0166,Plastic Component 005,Plastic Component,ABS Plastic,Medium,6.03,4581.27,0.40,A

Last 5 Rows:

,product_id,supplier_id,product_name,product_category,material,process_complexity,target_cycle_time_minutes,standard_unit_cost_inr,dimensional_tolerance_mm,quality_grade
145,PRD0146,SUP0045,Electrical Component 146,Electrical Component,Steel,Low,5.31,5011.95,0.47,C
146,PRD0147,SUP0113,Mechanical Part 147,Mechanical Part,Composite,Low,4.99,1169.20,0.17,B
147,PRD0148,SUP0058,Plastic Component 148,Plastic Component,Steel,High,4.18,5555.01,0.42,C
148,PRD0149,SUP0181,Automotive Part 149,Automotive Part,Copper,Medium,3.21,4356.00,0.10,B
149,PRD0150,SUP0201,Packaging Unit 150,Packaging Unit,Composite,High,6.56,2374.89,0.40,C

================================================================================
Dataset: Operators
================================================================================

Shape: (1000, 9)

Data Types:

operator_id                   str
operator_name                 str
factory_id                    str
primary_shift                 str
experience_years          float64
skill_level                   str
safety_training_status        str
attendance_rate           float64
operator_error_factor     float64
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   operator_id             1000 non-null   str
 1   operator_name           1000 non-null   str
 2   factory_id              1000 non-null   str
 3   primary_shift           1000 non-null   str
 4   experience_years        1000 non-null   float64
 5   skill_level             1000 non-null   str
 6   safety_training_status  1000 non-null   str
 7   attendance_rate         1000 non-null   float64
 8   operator_error_factor   1000 non-null   float64
dtypes: float64(3), str(6)
memory usage: 70.4 KB

First 5 Rows:

,operator_id,operator_name,factory_id,primary_shift,experience_years,skill_level,safety_training_status,attendance_rate,operator_error_factor
0,OPR0001,Priya Mehta,FAC007,Morning,16.90,Senior,Expired,0.89,0.03
1,OPR0002,Karan Patel,FAC008,Night,3.50,Intermediate,Certified,0.78,0.02
2,OPR0003,Neha Patel,FAC001,Night,13.40,Senior,Certified,0.81,0.01
3,OPR0004,Nitin Sharma,FAC004,Night,10.40,Senior,Certified,0.97,0.01
4,OPR0005,Arjun Patel,FAC007,Night,19.20,Senior,Expired,0.84,0.03

Last 5 Rows:

,operator_id,operator_name,factory_id,primary_shift,experience_years,skill_level,safety_training_status,attendance_rate,operator_error_factor
995,OPR0996,Simran Verma,FAC005,Evening,16.00,Senior,Certified,0.88,0.01
996,OPR0997,Ananya Patel,FAC010,Evening,18.00,Senior,Certified,0.87,0.01
997,OPR0998,Nitin Singh,FAC006,Evening,10.20,Senior,Certified,0.81,0.01
998,OPR0999,Aman Patel,FAC006,Evening,13.90,Senior,Certified,0.95,0.01
999,OPR1000,Aditya Singh,FAC002,Evening,16.50,Senior,Certified,0.79,0.01

================================================================================
Dataset: Production Batches
================================================================================

Shape: (60000, 24)

Data Types:

batch_id                         str
machine_id                       str
line_id                          str
factory_id                       str
product_id                       str
supplier_id                      str
operator_id                      str
production_date                  str
start_time                       str
shift                            str
planned_quantity               int64
units_produced                 int64
good_units                     int64
defective_units                int64
scrap_units                    int64
rework_units                   int64
runtime_hours                float64
downtime_hours               float64
availability_ratio           float64
actual_cycle_time_minutes    float64
energy_consumption_kwh       float64
scrap_cost_inr               float64
batch_status                     str
failure_near_batch             int64
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   batch_id                   60000 non-null  str
 1   machine_id                 60000 non-null  str
 2   line_id                    60000 non-null  str
 3   factory_id                 60000 non-null  str
 4   product_id                 60000 non-null  str
 5   supplier_id                60000 non-null  str
 6   operator_id                59550 non-null  str
 7   production_date            60000 non-null  str
 8   start_time                 60000 non-null  str
 9   shift                      60000 non-null  str
 10  planned_quantity           60000 non-null  int64
 11  units_produced             60000 non-null  int64
 12  good_units                 60000 non-null  int64
 13  defective_units            60000 non-null  int64
 14  scrap_units                60000 non-null  int64
 15  rework_units               60000 non-null  int64
 16  runtime_hours              60000 non-null  float64
 17  downtime_hours             60000 non-null  float64
 18  availability_ratio         60000 non-null  float64
 19  actual_cycle_time_minutes  60000 non-null  float64
 20  energy_consumption_kwh     60000 non-null  float64
 21  scrap_cost_inr             60000 non-null  float64
 22  batch_status               60000 non-null  str
 23  failure_near_batch         60000 non-null  int64
dtypes: float64(6), int64(7), str(11)
memory usage: 11.0 MB

First 5 Rows:

,batch_id,machine_id,line_id,factory_id,product_id,supplier_id,operator_id,production_date,start_time,shift,planned_quantity,units_produced,good_units,defective_units,scrap_units,rework_units,runtime_hours,downtime_hours,availability_ratio,actual_cycle_time_minutes,energy_consumption_kwh,scrap_cost_inr,batch_status,failure_near_batch
0,BAT000001,MCH0401,LIN015,FAC005,PRD0001,SUP0143,OPR0965,2024-01-25,12:27:27,Morning,1653,1228,1176,52,18,34,5.00,1.37,0.78,0.24,822.84,80950.93,Below Plan,0
1,BAT000002,MCH0394,LIN001,FAC001,PRD0123,SUP0009,OPR0886,2024-10-03,11:50:12,Evening,566,520,474,46,25,21,4.86,0.56,0.90,0.56,627.55,6867.73,Completed,0
2,BAT000003,MCH0359,LIN019,FAC007,PRD0096,SUP0028,OPR0275,2023-12-15,00:59:23,Night,317,276,254,22,13,9,10.83,1.61,0.87,2.35,821.55,29021.40,Below Plan,0
3,BAT000004,MCH0265,LIN011,FAC004,PRD0136,SUP0004,OPR0013,2023-06-24,10:32:47,Morning,1728,1681,1571,110,53,57,8.85,0.22,0.98,0.32,882.79,49370.78,Completed,0
4,BAT000005,MCH0480,LIN019,FAC007,PRD0135,SUP0043,OPR0220,2025-05-31,08:17:38,Night,1838,1818,1675,143,83,60,8.19,0.66,0.93,0.27,905.00,263690.01,Completed,0

Last 5 Rows:

,batch_id,machine_id,line_id,factory_id,product_id,supplier_id,operator_id,production_date,start_time,shift,planned_quantity,units_produced,good_units,defective_units,scrap_units,rework_units,runtime_hours,downtime_hours,availability_ratio,actual_cycle_time_minutes,energy_consumption_kwh,scrap_cost_inr,batch_status,failure_near_batch
59995,BAT059996,MCH0114,LIN004,FAC002,PRD0022,SUP0149,OPR0242,2026-06-09,21:56:38,Evening,1016,861,779,82,48,34,6.98,1.23,0.85,0.49,940.46,76584.58,Below Plan,0
59996,BAT059997,MCH0252,LIN027,FAC009,PRD0112,SUP0208,OPR0777,2026-05-01,22:11:17,Evening,2839,2391,2199,192,69,123,4.74,1.17,0.80,0.12,941.17,39573.40,Below Plan,0
59997,BAT059998,MCH0277,LIN001,FAC001,PRD0070,SUP0146,OPR0283,2023-07-28,09:33:20,Morning,2073,1647,1536,111,55,56,4.20,1.31,0.76,0.15,969.17,9349.98,Below Plan,0
59998,BAT059999,MCH0532,LIN007,FAC003,PRD0061,SUP0109,OPR0870,2025-01-25,00:34:43,Evening,1324,1046,951,95,37,58,11.64,2.19,0.84,0.67,1710.91,63349.54,Below Plan,0
59999,BAT060000,MCH0327,LIN009,FAC003,PRD0010,SUP0035,OPR0047,2024-09-12,02:29:55,Morning,1809,1402,1326,76,28,48,5.81,1.53,0.79,0.25,849.05,39518.69,Below Plan,0

================================================================================
Dataset: Sensor Readings
================================================================================

Shape: (285000, 17)

Data Types:

sensor_reading_id              str
machine_id                     str
line_id                        str
factory_id                     str
reading_timestamp              str
temperature_c              float64
vibration_mm_s             float64
pressure_bar               float64
oil_level_percent          float64
voltage_v                  float64
current_amp                float64
rpm                        float64
sound_level_db             float64
machine_health_score         int64
alert_status                   str
failure_within_7_days        int64
linked_failure_event_id        str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 285000 entries, 0 to 284999
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   sensor_reading_id        285000 non-null  str
 1   machine_id               285000 non-null  str
 2   line_id                  285000 non-null  str
 3   factory_id               285000 non-null  str
 4   reading_timestamp        285000 non-null  str
 5   temperature_c            283800 non-null  float64
 6   vibration_mm_s           285000 non-null  float64
 7   pressure_bar             285000 non-null  float64
 8   oil_level_percent        285000 non-null  float64
 9   voltage_v                285000 non-null  float64
 10  current_amp              285000 non-null  float64
 11  rpm                      285000 non-null  float64
 12  sound_level_db           285000 non-null  float64
 13  machine_health_score     285000 non-null  int64
 14  alert_status             285000 non-null  str
 15  failure_within_7_days    285000 non-null  int64
 16  linked_failure_event_id  7715 non-null    str
dtypes: float64(8), int64(2), str(7)
memory usage: 37.0 MB

First 5 Rows:

,sensor_reading_id,machine_id,line_id,factory_id,reading_timestamp,temperature_c,vibration_mm_s,pressure_bar,oil_level_percent,voltage_v,current_amp,rpm,sound_level_db,machine_health_score,alert_status,failure_within_7_days,linked_failure_event_id
0,SNS0000001,MCH0212,LIN030,FAC010,2025-01-28 19:38:45,33.25,3.69,5.33,76.90,412.77,33.29,878.20,71.68,82,Normal,0,NaN
1,SNS0000002,MCH0134,LIN006,FAC002,2026-05-05 18:25:04,60.37,3.18,5.04,85.60,413.53,38.28,1437.80,75.88,93,Normal,0,NaN
2,SNS0000003,MCH0227,LIN023,FAC008,2024-12-23 19:29:20,70.58,0.89,5.12,71.21,429.69,27.93,1762.90,69.30,97,Normal,0,NaN
3,SNS0000004,MCH0059,LIN012,FAC004,2023-05-17 02:02:47,42.87,2.90,3.83,63.01,430.38,28.13,746.30,69.73,88,Normal,0,NaN
4,SNS0000005,MCH0474,LIN003,FAC001,2025-08-10 14:59:02,60.29,4.68,6.27,73.69,409.80,44.78,1212.40,63.75,83,Normal,0,NaN

Last 5 Rows:

,sensor_reading_id,machine_id,line_id,factory_id,reading_timestamp,temperature_c,vibration_mm_s,pressure_bar,oil_level_percent,voltage_v,current_amp,rpm,sound_level_db,machine_health_score,alert_status,failure_within_7_days,linked_failure_event_id
284995,SNS0284996,MCH0264,LIN030,FAC010,2026-04-30 18:31:19,82.71,1.94,6.31,55.70,421.06,47.61,2046.60,79.42,83,Normal,0,NaN
284996,SNS0284997,MCH0030,LIN022,FAC008,2025-02-21 22:41:29,66.70,2.78,4.93,76.55,431.62,45.62,1831.70,74.70,90,Normal,0,NaN
284997,SNS0284998,MCH0238,LIN007,FAC003,2024-04-06 22:28:52,70.58,4.52,6.28,76.30,399.74,34.90,1182.30,75.04,86,Normal,0,NaN
284998,SNS0284999,MCH0376,LIN005,FAC002,2024-06-08 14:09:37,41.48,2.98,7.45,81.52,425.55,39.50,588.30,72.25,87,Normal,0,NaN
284999,SNS0285000,MCH0581,LIN004,FAC002,2023-11-16 11:24:32,62.67,4.00,6.91,72.24,414.43,42.41,836.70,69.80,92,Normal,0,NaN

================================================================================
Dataset: Maintenance Work Orders
================================================================================

Shape: (12000, 16)

Data Types:

work_order_id                     str
machine_id                        str
line_id                           str
factory_id                        str
linked_failure_event_id           str
scheduled_timestamp               str
completion_timestamp              str
maintenance_type                  str
maintenance_reason                str
action_taken                      str
maintenance_downtime_hours    float64
parts_cost_inr                float64
labor_cost_inr                float64
total_maintenance_cost_inr    float64
technician_id                     str
work_order_status                 str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   work_order_id               12000 non-null  str
 1   machine_id                  12000 non-null  str
 2   line_id                     12000 non-null  str
 3   factory_id                  12000 non-null  str
 4   linked_failure_event_id     3000 non-null   str
 5   scheduled_timestamp         12000 non-null  str
 6   completion_timestamp        12000 non-null  str
 7   maintenance_type            12000 non-null  str
 8   maintenance_reason          12000 non-null  str
 9   action_taken                12000 non-null  str
 10  maintenance_downtime_hours  12000 non-null  float64
 11  parts_cost_inr              12000 non-null  float64
 12  labor_cost_inr              12000 non-null  float64
 13  total_maintenance_cost_inr  12000 non-null  float64
 14  technician_id               12000 non-null  str
 15  work_order_status           12000 non-null  str
dtypes: float64(4), str(12)
memory usage: 1.5 MB

First 5 Rows:

,work_order_id,machine_id,line_id,factory_id,linked_failure_event_id,scheduled_timestamp,completion_timestamp,maintenance_type,maintenance_reason,action_taken,maintenance_downtime_hours,parts_cost_inr,labor_cost_inr,total_maintenance_cost_inr,technician_id,work_order_status
0,MWO000001,MCH0340,LIN012,FAC004,FLR001989,2025-10-03 06:50:27,2025-10-03 09:10:51,Corrective,Overheating,Inspection,2.34,20299.29,3370.41,23669.70,TECH067,Completed
1,MWO000002,MCH0459,LIN006,FAC002,FLR000903,2024-07-13 19:21:54,2024-07-13 21:11:06,Corrective,Bearing Failure,Calibration,1.82,16948.13,2161.39,19109.52,TECH060,Completed
2,MWO000003,MCH0470,LIN002,FAC001,FLR001426,2024-06-22 01:36:00,2024-06-22 11:34:12,Emergency,Sensor Failure,Replace Component,9.97,69284.59,15474.64,84759.23,TECH138,Completed
3,MWO000004,MCH0536,LIN030,FAC010,FLR002583,2026-03-01 22:00:30,2026-03-02 01:26:54,Corrective,Electrical Fault,Lubrication,3.44,12240.71,4715.12,16955.83,TECH089,Completed
4,MWO000005,MCH0160,LIN018,FAC006,FLR002948,2024-08-22 01:19:01,2024-08-22 09:22:01,Corrective,Excessive Vibration,Alignment,8.05,48792.04,11157.91,59949.95,TECH098,Completed

Last 5 Rows:

,work_order_id,machine_id,line_id,factory_id,linked_failure_event_id,scheduled_timestamp,completion_timestamp,maintenance_type,maintenance_reason,action_taken,maintenance_downtime_hours,parts_cost_inr,labor_cost_inr,total_maintenance_cost_inr,technician_id,work_order_status
11995,MWO011996,MCH0072,LIN011,FAC004,NaN,2025-11-08 19:27:44,2025-11-08 20:51:44,Preventive,Tool Wear,Electrical Repair,1.40,15086.67,2890.60,17977.27,TECH124,Completed
11996,MWO011997,MCH0567,LIN016,FAC006,NaN,2023-07-10 11:59:29,2023-07-10 17:03:41,Corrective,Rising Temperature,Replace Component,5.07,24174.95,6525.36,30700.31,TECH015,Completed
11997,MWO011998,MCH0432,LIN025,FAC009,NaN,2023-12-22 18:21:11,2023-12-22 21:46:23,Corrective,Calibration Due,Replace Component,3.42,25386.47,3404.53,28791.00,TECH049,Completed
11998,MWO011999,MCH0124,LIN013,FAC005,NaN,2025-05-19 01:52:40,2025-05-19 02:22:40,Preventive,Calibration Due,Alignment,0.50,24567.40,546.91,25114.31,TECH013,Cancelled
11999,MWO012000,MCH0199,LIN008,FAC003,NaN,2024-12-05 08:28:33,2024-12-05 13:45:57,Predictive,High Vibration,Electrical Repair,5.29,41082.18,9069.80,50151.98,TECH124,Completed

================================================================================
Dataset: Quality Inspections
================================================================================

Shape: (30000, 18)

Data Types:

inspection_id                     str
batch_id                          str
machine_id                        str
line_id                           str
factory_id                        str
product_id                        str
supplier_id                       str
operator_id                       str
inspection_date                   str
inspector_id                      str
sample_size                     int64
passed_samples                  int64
failed_samples                  int64
defect_type                       str
defect_severity                   str
measured_dimension_mm         float64
inspection_result                 str
estimated_quality_loss_inr    float64
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   inspection_id               30000 non-null  str
 1   batch_id                    30000 non-null  str
 2   machine_id                  30000 non-null  str
 3   line_id                     30000 non-null  str
 4   factory_id                  30000 non-null  str
 5   product_id                  30000 non-null  str
 6   supplier_id                 30000 non-null  str
 7   operator_id                 30000 non-null  str
 8   inspection_date             30000 non-null  str
 9   inspector_id                30000 non-null  str
 10  sample_size                 30000 non-null  int64
 11  passed_samples              30000 non-null  int64
 12  failed_samples              30000 non-null  int64
 13  defect_type                 30000 non-null  str
 14  defect_severity             29808 non-null  str
 15  measured_dimension_mm       30000 non-null  float64
 16  inspection_result           30000 non-null  str
 17  estimated_quality_loss_inr  30000 non-null  float64
dtypes: float64(2), int64(3), str(13)
memory usage: 4.1 MB

First 5 Rows:

,inspection_id,batch_id,machine_id,line_id,factory_id,product_id,supplier_id,operator_id,inspection_date,inspector_id,sample_size,passed_samples,failed_samples,defect_type,defect_severity,measured_dimension_mm,inspection_result,estimated_quality_loss_inr
0,QIN000001,BAT000278,MCH0212,LIN030,FAC010,PRD0100,SUP0119,OPR0248,2025-09-16,INS034,126,110,16,Burr,Minor,51.53,Fail,31024.34
1,QIN000002,BAT023553,MCH0490,LIN018,FAC006,PRD0052,SUP0067,OPR0065,2026-03-01,INS072,116,101,15,Electrical Failure,Minor,49.78,Fail,90365.47
2,QIN000003,BAT022788,MCH0162,LIN014,FAC005,PRD0016,SUP0177,OPR0137,2024-08-18,INS073,98,88,10,Porosity,Minor,50.14,Fail,40243.43
3,QIN000004,BAT038463,MCH0293,LIN023,FAC008,PRD0068,SUP0178,OPR0390,2025-06-07,INS040,102,86,16,Discoloration,Major,48.34,Fail,71586.36
4,QIN000005,BAT013874,MCH0073,LIN002,FAC001,PRD0013,SUP0182,OPR0889,2025-09-02,INS076,44,40,4,Porosity,Minor,48.87,Fail,347.44

Last 5 Rows:

,inspection_id,batch_id,machine_id,line_id,factory_id,product_id,supplier_id,operator_id,inspection_date,inspector_id,sample_size,passed_samples,failed_samples,defect_type,defect_severity,measured_dimension_mm,inspection_result,estimated_quality_loss_inr
29995,QIN029996,BAT027669,MCH0594,LIN016,FAC006,PRD0026,SUP0022,OPR0578,2023-05-24,INS017,53,47,6,Packaging Damage,Critical,49.08,Fail,4762.89
29996,QIN029997,BAT021355,MCH0215,LIN014,FAC005,PRD0002,SUP0183,OPR0603,2023-11-28,INS050,52,47,5,Misalignment,Minor,49.03,Fail,18661.14
29997,QIN029998,BAT034516,MCH0020,LIN001,FAC001,PRD0150,SUP0201,OPR0894,2024-11-24,INS016,247,218,29,Dimensional Error,Minor,50.34,Fail,17847.55
29998,QIN029999,BAT015177,MCH0227,LIN023,FAC008,PRD0011,SUP0200,OPR0279,2024-01-22,INS034,239,218,21,Electrical Failure,Minor,50.27,Fail,15915.27
29999,QIN030000,BAT019818,MCH0053,LIN007,FAC003,PRD0145,SUP0141,OPR0544,2024-09-29,INS001,125,115,10,Surface Crack,Minor,49.08,Fail,10814.76

================================================================================
Dataset: Downtime Events
================================================================================

Shape: (8000, 13)

Data Types:

downtime_event_id              str
machine_id                     str
line_id                        str
factory_id                     str
linked_failure_event_id        str
linked_work_order_id           str
event_timestamp                str
downtime_cause                 str
duration_hours             float64
estimated_lost_units         int64
estimated_loss_inr         float64
resolution_status              str
impact_level                   str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   downtime_event_id        8000 non-null   str
 1   machine_id               8000 non-null   str
 2   line_id                  8000 non-null   str
 3   factory_id               8000 non-null   str
 4   linked_failure_event_id  4296 non-null   str
 5   linked_work_order_id     8000 non-null   str
 6   event_timestamp          8000 non-null   str
 7   downtime_cause           8000 non-null   str
 8   duration_hours           8000 non-null   float64
 9   estimated_lost_units     8000 non-null   int64
 10  estimated_loss_inr       8000 non-null   float64
 11  resolution_status        8000 non-null   str
 12  impact_level             8000 non-null   str
dtypes: float64(2), int64(1), str(10)
memory usage: 812.6 KB

First 5 Rows:

,downtime_event_id,machine_id,line_id,factory_id,linked_failure_event_id,linked_work_order_id,event_timestamp,downtime_cause,duration_hours,estimated_lost_units,estimated_loss_inr,resolution_status,impact_level
0,DTE000001,MCH0296,LIN026,FAC009,FLR000001,MWO000001,2026-02-12 11:52:47,Machine Breakdown,4.96,549,398037.83,Resolved,Medium
1,DTE000002,MCH0573,LIN004,FAC002,FLR000002,MWO000002,2025-05-24 10:22:32,Machine Breakdown,4.01,634,671146.80,Resolved,High
2,DTE000003,MCH0388,LIN011,FAC004,FLR000003,MWO000003,2023-08-11 10:12:05,Machine Breakdown,10.37,2025,1574258.15,Resolved,Medium
3,DTE000004,MCH0202,LIN009,FAC003,FLR000004,MWO000004,2024-01-01 21:26:00,Machine Breakdown,17.13,3692,3308032.43,Resolved,Medium
4,DTE000005,MCH0321,LIN029,FAC010,FLR000005,MWO000005,2025-04-01 13:33:41,Machine Breakdown,5.65,651,409580.56,Resolved,Low

Last 5 Rows:

,downtime_event_id,machine_id,line_id,factory_id,linked_failure_event_id,linked_work_order_id,event_timestamp,downtime_cause,duration_hours,estimated_lost_units,estimated_loss_inr,resolution_status,impact_level
7995,DTE007996,MCH0177,LIN009,FAC003,NaN,MWO006243,2025-03-06 18:44:03,Tool Change,5.24,1167,1051654.18,Resolved,High
7996,DTE007997,MCH0594,LIN016,FAC006,NaN,MWO006801,2024-03-28 13:05:27,Material Shortage,1.60,259,61207.68,Resolved,High
7997,DTE007998,MCH0169,LIN003,FAC001,FLR000244,MWO002141,2026-04-25 05:19:51,Changeover,1.36,122,38322.58,Resolved,High
7998,DTE007999,MCH0218,LIN007,FAC003,FLR002665,MWO001674,2023-11-09 05:36:42,Power Failure,2.62,267,164023.29,Resolved,High
7999,DTE008000,MCH0217,LIN009,FAC003,NaN,MWO010896,2023-12-11 05:43:16,Changeover,0.91,63,25760.51,Resolved,Critical

================================================================================
Dataset: Failure Events
================================================================================

Shape: (3000, 11)

Data Types:

failure_event_id                  str
machine_id                        str
line_id                           str
factory_id                        str
failure_timestamp                 str
failure_mode                      str
failure_severity                  str
sensor_precursor_days           int64
repair_duration_hours         float64
estimated_failure_loss_inr    float64
resolution_status                 str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   failure_event_id            3000 non-null   str
 1   machine_id                  3000 non-null   str
 2   line_id                     3000 non-null   str
 3   factory_id                  3000 non-null   str
 4   failure_timestamp           3000 non-null   str
 5   failure_mode                3000 non-null   str
 6   failure_severity            3000 non-null   str
 7   sensor_precursor_days       3000 non-null   int64
 8   repair_duration_hours       3000 non-null   float64
 9   estimated_failure_loss_inr  3000 non-null   float64
 10  resolution_status           3000 non-null   str
dtypes: float64(2), int64(1), str(8)
memory usage: 257.9 KB

First 5 Rows:

,failure_event_id,machine_id,line_id,factory_id,failure_timestamp,failure_mode,failure_severity,sensor_precursor_days,repair_duration_hours,estimated_failure_loss_inr,resolution_status
0,FLR000001,MCH0296,LIN026,FAC009,2026-02-12 11:52:47,Tool Wear,Major,6,4.96,339981.62,Open
1,FLR000002,MCH0573,LIN004,FAC002,2025-05-24 10:22:32,Bearing Failure,Minor,2,4.01,132393.65,Open
2,FLR000003,MCH0388,LIN011,FAC004,2023-08-11 10:12:05,Sensor Failure,Critical,3,10.37,586745.98,Resolved
3,FLR000004,MCH0202,LIN009,FAC003,2024-01-01 21:26:00,Hydraulic Leak,Minor,7,17.13,1150036.04,Resolved
4,FLR000005,MCH0321,LIN029,FAC010,2025-04-01 13:33:41,Excessive Vibration,Major,4,5.65,586168.29,Resolved

Last 5 Rows:

,failure_event_id,machine_id,line_id,factory_id,failure_timestamp,failure_mode,failure_severity,sensor_precursor_days,repair_duration_hours,estimated_failure_loss_inr,resolution_status
2995,FLR002996,MCH0555,LIN021,FAC007,2023-10-28 12:37:45,Hydraulic Leak,Minor,5,8.10,840298.38,Open
2996,FLR002997,MCH0545,LIN004,FAC002,2024-10-15 11:39:15,Electrical Fault,Minor,3,11.57,532950.25,Resolved
2997,FLR002998,MCH0096,LIN010,FAC004,2023-02-21 04:19:54,Lubrication Failure,Minor,5,7.08,546839.86,Resolved
2998,FLR002999,MCH0361,LIN024,FAC008,2026-03-05 06:34:30,Lubrication Failure,Major,5,0.96,52047.58,Resolved
2999,FLR003000,MCH0403,LIN002,FAC001,2023-05-07 17:07:17,Hydraulic Leak,Minor,7,3.39,328759.61,Resolved

In [10]:
production_batches

,batch_id,machine_id,line_id,factory_id,product_id,supplier_id,operator_id,production_date,start_time,shift,planned_quantity,units_produced,good_units,defective_units,scrap_units,rework_units,runtime_hours,downtime_hours,availability_ratio,actual_cycle_time_minutes,energy_consumption_kwh,scrap_cost_inr,batch_status,failure_near_batch
0,BAT000001,MCH0401,LIN015,FAC005,PRD0001,SUP0143,OPR0965,2024-01-25,12:27:27,Morning,1653,1228,1176,52,18,34,5.00,1.37,0.78,0.24,822.84,80950.93,Below Plan,0
1,BAT000002,MCH0394,LIN001,FAC001,PRD0123,SUP0009,OPR0886,2024-10-03,11:50:12,Evening,566,520,474,46,25,21,4.86,0.56,0.90,0.56,627.55,6867.73,Completed,0
2,BAT000003,MCH0359,LIN019,FAC007,PRD0096,SUP0028,OPR0275,2023-12-15,00:59:23,Night,317,276,254,22,13,9,10.83,1.61,0.87,2.35,821.55,29021.40,Below Plan,0
3,BAT000004,MCH0265,LIN011,FAC004,PRD0136,SUP0004,OPR0013,2023-06-24,10:32:47,Morning,1728,1681,1571,110,53,57,8.85,0.22,0.98,0.32,882.79,49370.78,Completed,0
4,BAT000005,MCH0480,LIN019,FAC007,PRD0135,SUP0043,OPR0220,2025-05-31,08:17:38,Night,1838,1818,1675,143,83,60,8.19,0.66,0.93,0.27,905.00,263690.01,Completed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,BAT059996,MCH0114,LIN004,FAC002,PRD0022,SUP0149,OPR0242,2026-06-09,21:56:38,Evening,1016,861,779,82,48,34,6.98,1.23,0.85,0.49,940.46,76584.58,Below Plan,0
59996,BAT059997,MCH0252,LIN027,FAC009,PRD0112,SUP0208,OPR0777,2026-05-01,22:11:17,Evening,2839,2391,2199,192,69,123,4.74,1.17,0.80,0.12,941.17,39573.40,Below Plan,0
59997,BAT059998,MCH0277,LIN001,FAC001,PRD0070,SUP0146,OPR0283,2023-07-28,09:33:20,Morning,2073,1647,1536,111,55,56,4.20,1.31,0.76,0.15,969.17,9349.98,Below Plan,0
59998,BAT059999,MCH0532,LIN007,FAC003,PRD0061,SUP0109,OPR0870,2025-01-25,00:34:43,Evening,1324,1046,951,95,37,58,11.64,2.19,0.84,0.67,1710.91,63349.54,Below Plan,0
59999,BAT060000,MCH0327,LIN009,FAC003,PRD0010,SUP0035,OPR0047,2024-09-12,02:29:55,Morning,1809,1402,1326,76,28,48,5.81,1.53,0.79,0.25,849.05,39518.69,Below Plan,0

In [18]:
print(
    "Sensor Readings → Machines:",
    sensor_readings["machine_id"].isin(machines["machine_id"]).all()
)

print(
    "Production Batches → Products:",
    production_batches["product_id"].isin(products["product_id"]).all()
)

print(
    "Quality Inspections → Production Batches:",
    quality_inspections["batch_id"].isin(production_batches["batch_id"]).all()
)

Sensor Readings → Machines: True
Production Batches → Products: True
Quality Inspections → Production Batches: True